[platformio]
src_dir = src
include_dir = include
description = Vigil OS Phase 4 ESP32 hardware telemetry node.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -std=gnu++17
lib_deps =
  bblanchon/ArduinoJson@^6.21.5
